### ISSUE TITLE
Invalid \escape

### ISSUE THREAD

**Issue by kariminf** [kariminf/oop4coders#3]
`
Traceback (most recent call last):
  File "summary_extractor.py", line 74, in <module>
    sentences = get_sentences(lang, doc)
  File "summary_extractor.py", line 34, in get_sentences
    cont = json.load(open(path))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 537 column 270 (char 92910)
`

**Comment by kariminf** [comment]
My bad: the issue is not for this project :-1:
